services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dt_user
      POSTGRES_PASSWORD: dt_pass
      POSTGRES_DB: dt_db
    ports:
      - "5432:5432"
    volumes:
      - dt_pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: dt_fastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://dt_user:dt_pass@db:5432/dt_db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  dt_pgdata:
